version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "3000:3000"
    environment:
      MONGO_USERNAME: mongo_user
      MONGO_PASSWORD: mongo_pass
      MONGO_HOST: mongo
      MONGO_DATABASE: my_database
    depends_on:
      - mongo

  mongo:
    image: mongo:8.0.15-noble
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo_user
      MONGO_INITDB_ROOT_PASSWORD: mongo_pass
      MONGO_INITDB_DATABASE: my_database
    volumes:
      - ./todo-database:/data/db

volumes:
  mongo_data:
