# ---- Build Stage ----
FROM node:24.10.0-alpine3.22 AS build
WORKDIR /usr/src/app
COPY package-lock.json package.json ./
RUN npm install --omit=dev --ignore-scripts
COPY app.js routes.js server.js ./
COPY public ./public

# ---- Production Stage ----
FROM node:24.10.0-alpine3.22 AS production
RUN addgroup -S todo && adduser -S todo -G todo
WORKDIR /usr/src/app
COPY --from=build /usr/src/app /usr/src/app
USER todo
EXPOSE 3000
CMD ["node", "server.js"]
